-- Отдельный журнал Airpay: запрос сохраняется до сети, код — до выдачи пользователю.
CREATE TABLE IF NOT EXISTS supplier_hub_airpay.airpay_transactions (
    agent_transaction_id bigint PRIMARY KEY CHECK (agent_transaction_id > 0),
    preparation_key uuid NOT NULL,
    created_by text NOT NULL,
    service_id text NOT NULL,
    service_title text NOT NULL,
    account text NOT NULL,
    purchase_kind text NOT NULL CHECK (purchase_kind IN ('voucher', 'topup')),
    request_payload jsonb NOT NULL,
    service_snapshot jsonb NOT NULL,
    check_response jsonb,
    check_result jsonb,
    pay_request jsonb,
    pay_response jsonb,
    voucher_response jsonb,
    pin_code text NOT NULL DEFAULT '',
    state text NOT NULL DEFAULT 'prepared' CHECK (state IN ('prepared', 'checking', 'check_pending', 'check_failed', 'checked', 'processing', 'paid', 'failed')),
    amount numeric(11,2),
    currency text NOT NULL DEFAULT '',
    provider_transaction_id text NOT NULL DEFAULT '',
    provider_message text NOT NULL DEFAULT '',
    check_attempts integer NOT NULL DEFAULT 0,
    pay_attempts integer NOT NULL DEFAULT 0,
    voucher_attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (created_by, preparation_key)
);
